# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/citrica/ChicOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/citrica/ChicOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/citrica/ChicOS/CMakeFiles /mnt/c/citrica/ChicOS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/citrica/ChicOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ChicOS

# Build rule for target.
ChicOS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChicOS
.PHONY : ChicOS

# fast build rule for target.
ChicOS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/build
.PHONY : ChicOS/fast

src/chicos.o: src/chicos.c.o
.PHONY : src/chicos.o

# target to build an object file
src/chicos.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/chicos.c.o
.PHONY : src/chicos.c.o

src/chicos.i: src/chicos.c.i
.PHONY : src/chicos.i

# target to preprocess a source file
src/chicos.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/chicos.c.i
.PHONY : src/chicos.c.i

src/chicos.s: src/chicos.c.s
.PHONY : src/chicos.s

# target to generate assembly for a file
src/chicos.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/chicos.c.s
.PHONY : src/chicos.c.s

src/modules/io/file.o: src/modules/io/file.c.o
.PHONY : src/modules/io/file.o

# target to build an object file
src/modules/io/file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/io/file.c.o
.PHONY : src/modules/io/file.c.o

src/modules/io/file.i: src/modules/io/file.c.i
.PHONY : src/modules/io/file.i

# target to preprocess a source file
src/modules/io/file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/io/file.c.i
.PHONY : src/modules/io/file.c.i

src/modules/io/file.s: src/modules/io/file.c.s
.PHONY : src/modules/io/file.s

# target to generate assembly for a file
src/modules/io/file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/io/file.c.s
.PHONY : src/modules/io/file.c.s

src/modules/log/log.o: src/modules/log/log.c.o
.PHONY : src/modules/log/log.o

# target to build an object file
src/modules/log/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/log/log.c.o
.PHONY : src/modules/log/log.c.o

src/modules/log/log.i: src/modules/log/log.c.i
.PHONY : src/modules/log/log.i

# target to preprocess a source file
src/modules/log/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/log/log.c.i
.PHONY : src/modules/log/log.c.i

src/modules/log/log.s: src/modules/log/log.c.s
.PHONY : src/modules/log/log.s

# target to generate assembly for a file
src/modules/log/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/log/log.c.s
.PHONY : src/modules/log/log.c.s

src/modules/memory/arena.o: src/modules/memory/arena.c.o
.PHONY : src/modules/memory/arena.o

# target to build an object file
src/modules/memory/arena.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/memory/arena.c.o
.PHONY : src/modules/memory/arena.c.o

src/modules/memory/arena.i: src/modules/memory/arena.c.i
.PHONY : src/modules/memory/arena.i

# target to preprocess a source file
src/modules/memory/arena.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/memory/arena.c.i
.PHONY : src/modules/memory/arena.c.i

src/modules/memory/arena.s: src/modules/memory/arena.c.s
.PHONY : src/modules/memory/arena.s

# target to generate assembly for a file
src/modules/memory/arena.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/memory/arena.c.s
.PHONY : src/modules/memory/arena.c.s

src/modules/process/process.o: src/modules/process/process.c.o
.PHONY : src/modules/process/process.o

# target to build an object file
src/modules/process/process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/process/process.c.o
.PHONY : src/modules/process/process.c.o

src/modules/process/process.i: src/modules/process/process.c.i
.PHONY : src/modules/process/process.i

# target to preprocess a source file
src/modules/process/process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/process/process.c.i
.PHONY : src/modules/process/process.c.i

src/modules/process/process.s: src/modules/process/process.c.s
.PHONY : src/modules/process/process.s

# target to generate assembly for a file
src/modules/process/process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/process/process.c.s
.PHONY : src/modules/process/process.c.s

src/modules/schedduler/schedduler.o: src/modules/schedduler/schedduler.c.o
.PHONY : src/modules/schedduler/schedduler.o

# target to build an object file
src/modules/schedduler/schedduler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/schedduler/schedduler.c.o
.PHONY : src/modules/schedduler/schedduler.c.o

src/modules/schedduler/schedduler.i: src/modules/schedduler/schedduler.c.i
.PHONY : src/modules/schedduler/schedduler.i

# target to preprocess a source file
src/modules/schedduler/schedduler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/schedduler/schedduler.c.i
.PHONY : src/modules/schedduler/schedduler.c.i

src/modules/schedduler/schedduler.s: src/modules/schedduler/schedduler.c.s
.PHONY : src/modules/schedduler/schedduler.s

# target to generate assembly for a file
src/modules/schedduler/schedduler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/schedduler/schedduler.c.s
.PHONY : src/modules/schedduler/schedduler.c.s

src/modules/semaphore/semaphore.o: src/modules/semaphore/semaphore.c.o
.PHONY : src/modules/semaphore/semaphore.o

# target to build an object file
src/modules/semaphore/semaphore.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/semaphore/semaphore.c.o
.PHONY : src/modules/semaphore/semaphore.c.o

src/modules/semaphore/semaphore.i: src/modules/semaphore/semaphore.c.i
.PHONY : src/modules/semaphore/semaphore.i

# target to preprocess a source file
src/modules/semaphore/semaphore.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/semaphore/semaphore.c.i
.PHONY : src/modules/semaphore/semaphore.c.i

src/modules/semaphore/semaphore.s: src/modules/semaphore/semaphore.c.s
.PHONY : src/modules/semaphore/semaphore.s

# target to generate assembly for a file
src/modules/semaphore/semaphore.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/semaphore/semaphore.c.s
.PHONY : src/modules/semaphore/semaphore.c.s

src/modules/user/user.o: src/modules/user/user.c.o
.PHONY : src/modules/user/user.o

# target to build an object file
src/modules/user/user.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/user/user.c.o
.PHONY : src/modules/user/user.c.o

src/modules/user/user.i: src/modules/user/user.c.i
.PHONY : src/modules/user/user.i

# target to preprocess a source file
src/modules/user/user.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/user/user.c.i
.PHONY : src/modules/user/user.c.i

src/modules/user/user.s: src/modules/user/user.c.s
.PHONY : src/modules/user/user.s

# target to generate assembly for a file
src/modules/user/user.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/user/user.c.s
.PHONY : src/modules/user/user.c.s

src/modules/utils/list.o: src/modules/utils/list.c.o
.PHONY : src/modules/utils/list.o

# target to build an object file
src/modules/utils/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/utils/list.c.o
.PHONY : src/modules/utils/list.c.o

src/modules/utils/list.i: src/modules/utils/list.c.i
.PHONY : src/modules/utils/list.i

# target to preprocess a source file
src/modules/utils/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/utils/list.c.i
.PHONY : src/modules/utils/list.c.i

src/modules/utils/list.s: src/modules/utils/list.c.s
.PHONY : src/modules/utils/list.s

# target to generate assembly for a file
src/modules/utils/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/utils/list.c.s
.PHONY : src/modules/utils/list.c.s

src/modules/utils/utils.o: src/modules/utils/utils.c.o
.PHONY : src/modules/utils/utils.o

# target to build an object file
src/modules/utils/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/utils/utils.c.o
.PHONY : src/modules/utils/utils.c.o

src/modules/utils/utils.i: src/modules/utils/utils.c.i
.PHONY : src/modules/utils/utils.i

# target to preprocess a source file
src/modules/utils/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/utils/utils.c.i
.PHONY : src/modules/utils/utils.c.i

src/modules/utils/utils.s: src/modules/utils/utils.c.s
.PHONY : src/modules/utils/utils.s

# target to generate assembly for a file
src/modules/utils/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/src/modules/utils/utils.c.s
.PHONY : src/modules/utils/utils.c.s

test/test.o: test/test.c.o
.PHONY : test/test.o

# target to build an object file
test/test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/test/test.c.o
.PHONY : test/test.c.o

test/test.i: test/test.c.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/test/test.c.i
.PHONY : test/test.c.i

test/test.s: test/test.c.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChicOS.dir/build.make CMakeFiles/ChicOS.dir/test/test.c.s
.PHONY : test/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ChicOS"
	@echo "... src/chicos.o"
	@echo "... src/chicos.i"
	@echo "... src/chicos.s"
	@echo "... src/modules/io/file.o"
	@echo "... src/modules/io/file.i"
	@echo "... src/modules/io/file.s"
	@echo "... src/modules/log/log.o"
	@echo "... src/modules/log/log.i"
	@echo "... src/modules/log/log.s"
	@echo "... src/modules/memory/arena.o"
	@echo "... src/modules/memory/arena.i"
	@echo "... src/modules/memory/arena.s"
	@echo "... src/modules/process/process.o"
	@echo "... src/modules/process/process.i"
	@echo "... src/modules/process/process.s"
	@echo "... src/modules/schedduler/schedduler.o"
	@echo "... src/modules/schedduler/schedduler.i"
	@echo "... src/modules/schedduler/schedduler.s"
	@echo "... src/modules/semaphore/semaphore.o"
	@echo "... src/modules/semaphore/semaphore.i"
	@echo "... src/modules/semaphore/semaphore.s"
	@echo "... src/modules/user/user.o"
	@echo "... src/modules/user/user.i"
	@echo "... src/modules/user/user.s"
	@echo "... src/modules/utils/list.o"
	@echo "... src/modules/utils/list.i"
	@echo "... src/modules/utils/list.s"
	@echo "... src/modules/utils/utils.o"
	@echo "... src/modules/utils/utils.i"
	@echo "... src/modules/utils/utils.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

